server:
  port: 8888
  servlet:
    path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: root
  # 开发阶段关闭thymeleaf的模板缓存
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.java.pojo